name: Deploy to EC2 using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Backend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-be:latest ./docker/backend/Dockerfile
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-be:latest

    - name: Build and Push Frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-fe:latest ./docker/frontend/Dockerfile
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-fe:latest

  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Pull latest images and restart services
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /test-deployment
          docker compose pull
          docker compose up -d
        EOF
